apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - service-external-name.yaml
  - ingress.yaml

images:
  - name: registry.registry.svc.cluster.local:5000/prospectos-frontend-app
    newTag: latest
