apiVersion: v1
kind: Service
metadata:
  name: openwa-api-service
  namespace: backend-ns
  labels:
    app: openwa-api
spec:
  selector:
    app: openwa-api
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 2785
  type: ClusterIP
