apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prospectos-postgres-data-pvc
  namespace: backend-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ceph-block
