apiVersion: v1
kind: Service
metadata:
  name: prospectos-postgres-service
  namespace: backend-ns
  labels:
    app: prospectos-postgres-db
spec:
  selector:
    app: prospectos-postgres-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
