apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configMap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml

images:
  - name: registry.registry.svc.cluster.local:5000/prospectos-backend-app
    newTag: latest
